I had a hard time implementing the R file into git and opening the github from there. After I watched a youtube tutorial I now understand it. 

---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

Step 12.2
Isaac: Used the existing lab 1 repository and copied the HTTP url.

Step 12.3
Isaac: Created a new project and cloned the lab 1 repository into it.
Sean: Cloned the repo from Github using Github CLI
Aiden: Cloned the project into R-Studio, no issues


Step 12.4
Isaac: Adding commits and pushed changes
Sean: Commit additions to readme 
Aiden: Commit my readme changes, no issues

Step 12.5 & 12.6
Isaac: Final Commits and Pushes
Sean: Pushing commits
Aiden: Pushed and made sure it worked, push didn't work first time because I made a mistake but worked 2nd time.
